PROJECT_ROLE_CATALOG = [
    {
        "code": "project_admin",
        "label": "Admin Proyek",
        "category": "governance",
        "category_label": "Project Governance",
        "default_division": "Project Administration",
        "responsibility": "Mengelola konfigurasi proyek di sistem, struktur role proyek, membership, dan koordinasi administrasi aplikasi proyek.",
        "access_hint": "Project administration, user assignment, role governance, project setup.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "project_sponsor",
        "label": "Project Sponsor",
        "category": "executive",
        "category_label": "Owner & Executive",
        "default_division": "Owner / Executive",
        "responsibility": "Menetapkan tujuan proyek, menyetujui keputusan strategis, dan menjaga dukungan organisasi.",
        "access_hint": "Executive oversight, escalation, approval, dashboard.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "owner_rep",
        "label": "Owner Representative",
        "category": "executive",
        "category_label": "Owner & Executive",
        "default_division": "Owner / Executive",
        "responsibility": "Mewakili owner/client untuk arahan, keputusan, dan penerimaan milestone.",
        "access_hint": "Project visibility, approvals, communication.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "client_stakeholder",
        "label": "Client Stakeholder",
        "category": "executive",
        "category_label": "Owner & Executive",
        "default_division": "Owner / Executive",
        "responsibility": "Memberi input kebutuhan bisnis, review deliverable, dan menerima update status.",
        "access_hint": "Limited project visibility and communication.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "project_manager",
        "label": "Project Manager",
        "category": "management",
        "category_label": "Project Management",
        "default_division": "Project Management",
        "responsibility": "Memimpin delivery proyek, koordinasi lintas divisi, risiko, eskalasi, dan keputusan harian.",
        "access_hint": "Full project operation, reports, approvals, controls.",
        "can_be_task_pic": True,
        "requires_division": False,
    },
    {
        "code": "deputy_pm",
        "label": "Deputy Project Manager",
        "category": "management",
        "category_label": "Project Management",
        "default_division": "Project Management",
        "responsibility": "Membantu PM mengelola operasi proyek dan menggantikan PM pada area yang didelegasikan.",
        "access_hint": "Project operation, communication, assigned approvals.",
        "can_be_task_pic": True,
        "requires_division": False,
    },
    {
        "code": "construction_manager",
        "label": "Construction Manager",
        "category": "management",
        "category_label": "Project Management",
        "default_division": "Site Management",
        "responsibility": "Mengendalikan pelaksanaan konstruksi, urutan pekerjaan, resource lapangan, dan produktivitas.",
        "access_hint": "Site tasks, lookahead, reports, blockers.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "site_manager",
        "label": "Site Manager",
        "category": "management",
        "category_label": "Project Management",
        "default_division": "Site Management",
        "responsibility": "Mengatur operasi site harian, koordinasi supervisor, dan kesiapan pekerjaan.",
        "access_hint": "Site execution, daily reports, coordination.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "division_lead",
        "label": "Division Lead",
        "category": "management",
        "category_label": "Project Management",
        "default_division": "Project Division",
        "responsibility": "Memimpin divisi proyek, membagi pekerjaan, review laporan tim, dan menjadi titik koordinasi divisi.",
        "access_hint": "Division tasks, reports, communication, approvals delegated by PM.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "project_engineer",
        "label": "Project Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Engineering",
        "responsibility": "Menghubungkan desain, metode kerja, dokumen teknis, dan pelaksanaan lapangan.",
        "access_hint": "Technical tasks, RFIs, drawings, reports.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "site_engineer",
        "label": "Site Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Engineering",
        "responsibility": "Mengarahkan pekerjaan teknis lapangan, membaca gambar, dan memastikan pekerjaan sesuai spesifikasi.",
        "access_hint": "Assigned WBS, daily reports, inspections.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "field_engineer",
        "label": "Field Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Engineering",
        "responsibility": "Menyelesaikan isu teknis lapangan, pengukuran, dan koordinasi detail pekerjaan.",
        "access_hint": "Assigned tasks, field evidence, RFIs.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "structural_engineer",
        "label": "Structural Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Engineering",
        "responsibility": "Meninjau aspek struktur, shop drawing, metode, dan ketidaksesuaian struktur.",
        "access_hint": "Technical review, drawings, NCR/RFI.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "mep_engineer",
        "label": "MEP Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "MEP",
        "responsibility": "Mengelola pekerjaan mechanical, electrical, plumbing, testing, dan koordinasi clash.",
        "access_hint": "MEP WBS, inspections, RFIs, submittals.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "architect_engineer",
        "label": "Architectural Engineer",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Architecture",
        "responsibility": "Mengelola pekerjaan arsitektur, finishing, material approval, dan detail gambar.",
        "access_hint": "Architectural WBS, drawings, material approvals.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "drafter",
        "label": "Drafter",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Engineering",
        "responsibility": "Membuat dan merevisi drawing, shop drawing, as-built, dan detail teknis.",
        "access_hint": "Drawing documents, revision tasks, RFIs.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "bim_modeler",
        "label": "BIM Modeler",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "BIM / Digital Engineering",
        "responsibility": "Mengelola model BIM, koordinasi clash, quantity extraction, dan integrasi drawing.",
        "access_hint": "BIM coordination, drawings, document control.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "surveyor",
        "label": "Surveyor",
        "category": "engineering",
        "category_label": "Engineering & Design",
        "default_division": "Survey",
        "responsibility": "Mengukur, setting out, kontrol elevasi, dan menyediakan data survey lapangan.",
        "access_hint": "Assigned tasks, daily reports, evidence.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "planning_engineer",
        "label": "Planning Engineer",
        "category": "controls",
        "category_label": "Planning & Controls",
        "default_division": "Planning & Controls",
        "responsibility": "Menyusun baseline schedule, lookahead, monitoring progress, dan analisis delay.",
        "access_hint": "Schedule, lookahead, progress, risks.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "scheduler",
        "label": "Scheduler",
        "category": "controls",
        "category_label": "Planning & Controls",
        "default_division": "Planning & Controls",
        "responsibility": "Memelihara jadwal, dependency, critical path, dan update forecast.",
        "access_hint": "Schedule and project controls.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "cost_controller",
        "label": "Cost Controller",
        "category": "controls",
        "category_label": "Planning & Controls",
        "default_division": "Cost Control",
        "responsibility": "Mengendalikan budget, actual cost, cost variance, dan cashflow proyek.",
        "access_hint": "Cost controls, progress claims, restricted financial data.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "quantity_surveyor",
        "label": "Quantity Surveyor",
        "category": "controls",
        "category_label": "Planning & Controls",
        "default_division": "Quantity Surveying",
        "responsibility": "Mengelola BOQ, volume aktual, progress claim, variation order, dan quantity reconciliation.",
        "access_hint": "BOQ, progress volume, claims, VO.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "doc_controller",
        "label": "Document Controller",
        "category": "controls",
        "category_label": "Planning & Controls",
        "default_division": "Document Control",
        "responsibility": "Mengelola register dokumen, distribusi drawing, revisi, transmittal, dan handover dossier.",
        "access_hint": "Documents, revisions, handover, communication.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "qa_qc_manager",
        "label": "QA/QC Manager",
        "category": "quality_safety",
        "category_label": "Quality & Safety",
        "default_division": "QA/QC",
        "responsibility": "Memimpin quality plan, ITP, inspection strategy, NCR, dan acceptance process.",
        "access_hint": "Inspections, NCR, material approval, reports.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "qa_qc_engineer",
        "label": "QA/QC Engineer",
        "category": "quality_safety",
        "category_label": "Quality & Safety",
        "default_division": "QA/QC",
        "responsibility": "Menyiapkan inspection request, test result, checklist, dan verifikasi requirement.",
        "access_hint": "Inspection, reports, evidence, NCR.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "inspector",
        "label": "Inspector",
        "category": "quality_safety",
        "category_label": "Quality & Safety",
        "default_division": "QA/QC",
        "responsibility": "Melakukan pemeriksaan lapangan, mencatat temuan, dan memverifikasi bukti pekerjaan.",
        "access_hint": "Inspection tasks, evidence, checklist.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "hse_manager",
        "label": "HSE Manager",
        "category": "quality_safety",
        "category_label": "Quality & Safety",
        "default_division": "HSE",
        "responsibility": "Memimpin keselamatan kerja, risk assessment, incident response, dan compliance HSE.",
        "access_hint": "HSE inspections, incidents, risks, reports.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "hse_officer",
        "label": "HSE Officer",
        "category": "quality_safety",
        "category_label": "Quality & Safety",
        "default_division": "HSE",
        "responsibility": "Melakukan patrol HSE, toolbox meeting, laporan safety, dan tindak lanjut temuan.",
        "access_hint": "HSE tasks, daily evidence, incident reports.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "contract_manager",
        "label": "Contract Manager",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Commercial / Contract",
        "responsibility": "Mengelola kontrak, klaim, perubahan lingkup, korespondensi formal, dan risiko komersial.",
        "access_hint": "Contract, claims, VO, formal communication.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "finance_manager",
        "label": "Finance Manager",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Finance & Accounting",
        "responsibility": "Mengelola cashflow proyek, invoice, pembayaran, pajak, rekonsiliasi, dan kontrol finansial proyek.",
        "access_hint": "Project financials, invoices, payment tracking, cost dashboards.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "project_accountant",
        "label": "Project Accountant",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Finance & Accounting",
        "responsibility": "Mencatat transaksi proyek, biaya aktual, invoice, payment status, dan dokumen akuntansi proyek.",
        "access_hint": "Project cost entries, invoices, payment documents, accounting records.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "procurement_manager",
        "label": "Procurement Manager",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Procurement",
        "responsibility": "Mengelola strategi pengadaan, vendor, lead time material, dan approval procurement.",
        "access_hint": "Material approvals, vendor/submittal, logistics.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "procurement_officer",
        "label": "Procurement Officer",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Procurement",
        "responsibility": "Menjalankan pembelian, follow-up vendor, dokumen pengadaan, dan status pengiriman.",
        "access_hint": "Material status, purchase documents, communication.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "logistics_coord",
        "label": "Logistics Coordinator",
        "category": "commercial",
        "category_label": "Commercial & Procurement",
        "default_division": "Logistics",
        "responsibility": "Mengatur penerimaan material, penyimpanan, distribusi ke area kerja, dan alat bantu.",
        "access_hint": "Material delivery, warehouse, field requests.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "supervisor",
        "label": "Supervisor",
        "category": "field",
        "category_label": "Field Execution",
        "default_division": "Site Execution",
        "responsibility": "Mengawasi pekerjaan harian, tenaga kerja, metode pelaksanaan, dan output lapangan.",
        "access_hint": "Assigned WBS, daily reports, manpower, evidence.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "foreman",
        "label": "Foreman / Mandor",
        "category": "field",
        "category_label": "Field Execution",
        "default_division": "Site Execution",
        "responsibility": "Mengatur kelompok kerja, output harian, kebutuhan material, dan laporan aktivitas.",
        "access_hint": "Assigned tasks, Telegram reports, evidence.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "field_staff",
        "label": "Field Staff",
        "category": "field",
        "category_label": "Field Execution",
        "default_division": "Site Execution",
        "responsibility": "Membantu pelaporan, dokumentasi lapangan, checklist, dan koordinasi pekerjaan.",
        "access_hint": "Assigned tasks, reports, evidence.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "staff",
        "label": "Staff",
        "category": "field",
        "category_label": "Field Execution",
        "default_division": "Project Team",
        "responsibility": "Melaksanakan pekerjaan, membuat update, mengunggah evidence, dan mengikuti task yang ditugaskan.",
        "access_hint": "Assigned tasks, reports, evidence, communication.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "warehouse_keeper",
        "label": "Warehouse Keeper",
        "category": "field",
        "category_label": "Field Execution",
        "default_division": "Warehouse",
        "responsibility": "Mengelola stok material, penerimaan, pengeluaran, dan bukti logistik.",
        "access_hint": "Material status, delivery evidence, requests.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "subcontractor",
        "label": "Subcontractor",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "Subcontractor",
        "responsibility": "Melaksanakan paket kerja sesuai kontrak, membuat laporan, dan memenuhi requirement evidence.",
        "access_hint": "Assigned package, daily reports, submittals.",
        "can_be_task_pic": True,
        "requires_division": True,
    },
    {
        "code": "vendor",
        "label": "Vendor / Supplier",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "Vendor / Supplier",
        "responsibility": "Menyediakan material, dokumen teknis, sertifikat, dan status pengiriman.",
        "access_hint": "Material submittals and delivery communication.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "consultant",
        "label": "Consultant",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "Consultant",
        "responsibility": "Memberikan review teknis, pengawasan, rekomendasi, atau approval sesuai kontrak.",
        "access_hint": "Reviews, RFIs, inspections, formal responses.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "authority_reviewer",
        "label": "Authority Reviewer",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "Authorities",
        "responsibility": "Meninjau izin, compliance, dokumen regulasi, dan approval eksternal.",
        "access_hint": "Limited document/review access.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "auditor",
        "label": "Auditor",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "Audit",
        "responsibility": "Melakukan audit proses, dokumen, bukti, dan kepatuhan proyek.",
        "access_hint": "Read/audit trail access according to policy.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
    {
        "code": "viewer",
        "label": "Viewer / Observer",
        "category": "external",
        "category_label": "External Parties",
        "default_division": "External Viewer",
        "responsibility": "Melihat status terbatas tanpa menjadi penanggung jawab pekerjaan.",
        "access_hint": "Read-only visibility according to RBAC.",
        "can_be_task_pic": False,
        "requires_division": False,
    },
]

PROJECT_MEMBER_ROLE_CODES = {item["code"] for item in PROJECT_ROLE_CATALOG}
PROJECT_ROLE_BY_CODE = {item["code"]: item for item in PROJECT_ROLE_CATALOG}

PROJECT_CROSS_DIVISION_ROLE_CODES = {
    "project_admin",
    "project_sponsor",
    "owner_rep",
    "project_manager",
    "deputy_pm",
    "construction_manager",
    "site_manager",
    "planning_engineer",
    "scheduler",
    "cost_controller",
    "quantity_surveyor",
    "doc_controller",
    "finance_manager",
    "project_accountant",
    "qa_qc_manager",
    "hse_manager",
    "contract_manager",
    "procurement_manager",
    "consultant",
    "auditor",
}

PROJECT_FINANCIAL_ROLE_CODES = {
    "cost_controller",
    "quantity_surveyor",
    "contract_manager",
    "finance_manager",
    "project_accountant",
}

PROJECT_DIVISION_LEAD_ROLE_CODES = {
    "division_lead",
    "construction_manager",
    "site_manager",
    "qa_qc_manager",
    "hse_manager",
    "planning_engineer",
}


def is_valid_project_role(project_role: str | None) -> bool:
    return bool(project_role and project_role in PROJECT_MEMBER_ROLE_CODES)


def project_role_label(project_role: str | None) -> str:
    if not project_role:
        return "Unassigned"
    return PROJECT_ROLE_BY_CODE.get(project_role, {}).get("label", project_role.replace("_", " ").title())


def role_requires_division(project_role: str | None) -> bool:
    return bool(PROJECT_ROLE_BY_CODE.get(project_role or "", {}).get("requires_division", True))


def role_can_be_task_pic(project_role: str | None) -> bool:
    return bool(PROJECT_ROLE_BY_CODE.get(project_role or "", {}).get("can_be_task_pic", False))


def is_cross_division_project_role(project_role: str | None) -> bool:
    return bool(project_role and project_role in PROJECT_CROSS_DIVISION_ROLE_CODES)


def is_division_lead_project_role(project_role: str | None) -> bool:
    return bool(project_role and project_role in PROJECT_DIVISION_LEAD_ROLE_CODES)


def can_role_access_task_division(project_role: str | None, membership_division_id: int | None, task_division_id: int | None) -> bool:
    if is_cross_division_project_role(project_role):
        return True
    if is_division_lead_project_role(project_role):
        return membership_division_id == task_division_id
    return membership_division_id == task_division_id


def is_financial_project_role(project_role: str | None) -> bool:
    return bool(project_role and project_role in PROJECT_FINANCIAL_ROLE_CODES)