import { Approval, AuditLog, CommunicationItem, DailyReport, Notification, Project, Task, User } from '@/types'

const now = new Date('2026-05-16T09:00:00+07:00')

function daysFromNow(days: number) {
  const date = new Date(now)
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

export const demoProjects: Project[] = [
  {
    id: 1,
    project_name: 'Jakarta Central Tower',
    description: 'Pembangunan mixed-use tower 45 lantai dengan 5 basement.',
    location: 'Jakarta Selatan',
    contract_value: 150_000_000_000,
    start_date: '2026-01-15T00:00:00Z',
    end_date: '2027-08-30T00:00:00Z',
    status: 'active',
    owner_id: 2,
    progress_percent: 42,
    created_at: '2026-01-05T08:00:00Z',
  },
  {
    id: 2,
    project_name: 'Tol Serpong Paket 3',
    description: 'Pekerjaan struktur jalan, drainase, dan jembatan pendek.',
    location: 'Tangerang Selatan',
    contract_value: 84_500_000_000,
    start_date: '2026-02-01T00:00:00Z',
    end_date: '2026-12-20T00:00:00Z',
    status: 'active',
    owner_id: 3,
    progress_percent: 58,
    created_at: '2026-01-20T08:00:00Z',
  },
  {
    id: 3,
    project_name: 'RS Modular Bandung',
    description: 'Paket modular ward, MEP, dan finishing area klinis.',
    location: 'Bandung',
    contract_value: 62_000_000_000,
    start_date: '2026-03-10T00:00:00Z',
    end_date: '2026-11-10T00:00:00Z',
    status: 'planning',
    owner_id: 2,
    progress_percent: 18,
    created_at: '2026-02-28T08:00:00Z',
  },
]

export const demoUsers: User[] = [
  {
    id: 1,
    name: 'Ahmad Rizki',
    email: 'admin@cpmis.id',
    role: 'admin',
    phone: '+62 812 1000 1000',
    telegram_id: '11010001',
    is_active: true,
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 2,
    name: 'Budi Santoso',
    email: 'director@cpmis.id',
    role: 'director',
    phone: '+62 812 2000 2000',
    telegram_id: '11010002',
    is_active: true,
    created_at: '2026-01-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'Siti Lestari',
    email: 'manager@cpmis.id',
    role: 'manager',
    phone: '+62 812 3000 3000',
    telegram_id: '11010003',
    is_active: true,
    created_at: '2026-01-02T08:00:00Z',
  },
  {
    id: 4,
    name: 'Andi Pratama',
    email: 'staff1@cpmis.id',
    role: 'staff',
    phone: '+62 812 4000 4000',
    telegram_id: '11010004',
    is_active: true,
    created_at: '2026-01-02T08:00:00Z',
  },
  {
    id: 5,
    name: 'Dewi Anggraini',
    email: 'staff2@cpmis.id',
    role: 'staff',
    phone: '+62 812 5000 5000',
    is_active: true,
    created_at: '2026-01-03T08:00:00Z',
  },
]

export const demoTasks: Task[] = [
  {
    id: 101,
    title: 'Review kontrak tender dan daftar deliverable',
    description: 'Validasi scope pekerjaan, milestone, penalti, dan dokumen wajib.',
    project_id: 1,
    division_id: 1,
    assigned_to: 3,
    created_by: 1,
    priority: 'critical',
    status: 'review',
    deadline: daysFromNow(-2),
    progress_percent: 80,
    ai_generated: true,
    requirements: [],
    materials: [],
    created_at: daysFromNow(-24),
  },
  {
    id: 102,
    title: 'Koordinasi clash MEP basement B2',
    description: 'Rute conduit berbenturan dengan opening struktur.',
    project_id: 1,
    division_id: 3,
    assigned_to: 4,
    created_by: 3,
    priority: 'high',
    status: 'blocked',
    deadline: daysFromNow(1),
    progress_percent: 45,
    ai_generated: false,
    requirements: [],
    materials: [],
    created_at: daysFromNow(-12),
  },
  {
    id: 103,
    title: 'Submit laporan progress bored pile zona C',
    description: 'Lengkapi volume harian, foto lapangan, dan kendala alat.',
    project_id: 2,
    division_id: 2,
    assigned_to: 4,
    created_by: 3,
    priority: 'medium',
    status: 'in_progress',
    deadline: daysFromNow(3),
    progress_percent: 62,
    ai_generated: true,
    requirements: [],
    materials: [],
    created_at: daysFromNow(-8),
  },
  {
    id: 104,
    title: 'Finalisasi shop drawing modular ward',
    description: 'Kirim revisi arsitektur dan koordinasi titik MEP.',
    project_id: 3,
    division_id: 4,
    assigned_to: 5,
    created_by: 3,
    priority: 'high',
    status: 'todo',
    deadline: daysFromNow(6),
    progress_percent: 15,
    ai_generated: true,
    requirements: [],
    materials: [],
    created_at: daysFromNow(-4),
  },
  {
    id: 105,
    title: 'Inspeksi QA/QC hasil cor slab B1',
    description: 'Verifikasi slump, sample kubus, dan checklist curing.',
    project_id: 1,
    division_id: 5,
    assigned_to: 5,
    created_by: 3,
    priority: 'critical',
    status: 'done',
    deadline: daysFromNow(-1),
    progress_percent: 100,
    ai_generated: false,
    requirements: [],
    materials: [],
    created_at: daysFromNow(-10),
  },
]

export const demoReports: DailyReport[] = [
  {
    id: 201,
    project_id: 1,
    user_id: 4,
    report_date: daysFromNow(-1),
    report_text: 'Pekerjaan slab B1 selesai 85 persen. Kendala utama adalah antrian concrete truck dan koordinasi jalur conduit.',
    weather: 'cerah',
    manpower_count: 38,
    ai_summary: 'Progress struktur baik, tetapi koordinasi MEP perlu dipercepat agar tidak menahan pekerjaan lanjutan.',
    ai_risks: 'Risiko delay 2-3 hari pada area basement bila clash MEP tidak selesai dalam 24 jam.',
    evidence: [],
    reviews: [],
    requirement_checks: [],
    created_at: daysFromNow(-1),
  },
  {
    id: 202,
    project_id: 2,
    user_id: 4,
    report_date: daysFromNow(-2),
    report_text: 'Mobilisasi alat berat zona C sudah lengkap. Drainase sementara perlu tambahan pompa karena curah hujan tinggi.',
    weather: 'hujan',
    manpower_count: 27,
    ai_summary: 'Mobilisasi siap, namun mitigasi genangan harus ditingkatkan sebelum pengecoran.',
    ai_risks: 'Risiko produktivitas turun bila pompa tambahan belum tersedia saat hujan.',
    evidence: [],
    reviews: [],
    requirement_checks: [],
    created_at: daysFromNow(-2),
  },
  {
    id: 203,
    project_id: 3,
    user_id: 5,
    report_date: daysFromNow(-3),
    report_text: 'Kickoff teknis modular ward selesai. Vendor meminta freeze desain ceiling sebelum fabrikasi.',
    weather: 'berawan',
    manpower_count: 16,
    ai_summary: 'Keputusan desain ceiling menjadi dependency utama untuk fabrikasi modular.',
    ai_risks: 'Risiko perubahan scope bila approval desain terlambat.',
    evidence: [],
    reviews: [],
    requirement_checks: [],
    created_at: daysFromNow(-3),
  },
]

export const demoNotifications: Notification[] = [
  {
    id: 301,
    title: 'Risk alert: clash MEP',
    message: 'Task koordinasi MEP basement B2 masuk status blocked dan perlu eskalasi.',
    type: 'warning',
    is_read: false,
    related_task_id: 102,
    related_project_id: 1,
    sent_to_telegram: true,
    created_at: daysFromNow(-1),
  },
  {
    id: 302,
    title: 'Tender analyzed',
    message: 'AI berhasil membuat task awal dari dokumen tender Jakarta Central Tower.',
    type: 'info',
    is_read: false,
    related_project_id: 1,
    sent_to_telegram: true,
    created_at: daysFromNow(-4),
  },
  {
    id: 303,
    title: 'Weekly summary ready',
    message: 'Ringkasan mingguan siap dikirim ke director dan stakeholder.',
    type: 'deadline',
    is_read: true,
    related_project_id: 2,
    sent_to_telegram: false,
    created_at: daysFromNow(-5),
  },
]

export const demoApprovals: Approval[] = [
  {
    id: 401,
    project_id: 1,
    requested_by: 3,
    approver_id: 2,
    title: 'Approval revisi rute MEP basement B2',
    description: 'Koordinasi clash membutuhkan persetujuan rute conduit baru sebelum pekerjaan lanjut.',
    approval_type: 'instruction',
    status: 'pending',
    related_entity_type: 'task',
    related_entity_id: 102,
    due_date: daysFromNow(1),
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
  {
    id: 402,
    project_id: 3,
    requested_by: 5,
    approver_id: 3,
    title: 'Freeze desain ceiling modular ward',
    description: 'Vendor meminta approval desain ceiling sebelum fabrikasi dimulai.',
    approval_type: 'scope_change',
    status: 'approved',
    related_entity_type: 'report',
    related_entity_id: 203,
    decision_note: 'Disetujui dengan catatan koordinasi ulang titik sprinkler.',
    decided_by: 3,
    decided_at: daysFromNow(-2),
    created_at: daysFromNow(-3),
    updated_at: daysFromNow(-2),
  },
  {
    id: 403,
    project_id: 2,
    requested_by: 4,
    approver_id: 3,
    title: 'Tambahan pompa drainase sementara',
    description: 'Cuaca hujan meningkatkan risiko genangan pada zona C.',
    approval_type: 'task',
    status: 'rejected',
    decision_note: 'Ditolak sementara, gunakan pompa existing dan evaluasi ulang besok.',
    decided_by: 3,
    decided_at: daysFromNow(-1),
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-1),
  },
]

export const demoAuditLogs: AuditLog[] = [
  {
    id: 501,
    actor_id: 3,
    project_id: 1,
    action: 'approval.created',
    entity_type: 'approval',
    entity_id: '401',
    summary: 'Approval dibuat: Approval revisi rute MEP basement B2',
    channel: 'web',
    created_at: daysFromNow(-1),
  },
  {
    id: 502,
    actor_id: 4,
    project_id: 1,
    action: 'task.status_changed',
    entity_type: 'task',
    entity_id: '102',
    summary: 'Status task berubah: Koordinasi clash MEP basement B2',
    channel: 'web',
    created_at: daysFromNow(-1),
  },
  {
    id: 503,
    actor_id: 1,
    project_id: 1,
    action: 'document.qa',
    entity_type: 'document',
    summary: 'Document QA: risiko utama dari kontrak basement',
    channel: 'web',
    created_at: daysFromNow(-2),
  },
]

export const demoCommunications: CommunicationItem[] = [
  {
    id: 601,
    project_id: 1,
    created_by: 4,
    assigned_to: 3,
    communication_type: 'rfi',
    status: 'open',
    priority: 'high',
    subject: 'RFI-001 Klarifikasi detail pile cap zona A',
    description: 'Staff lapangan perlu jawaban sebelum pekerjaan bekisting dilanjutkan.',
    question: 'Dimensi pembesian pile cap pada drawing revisi terakhir berbeda dengan BOQ.',
    discipline: 'Struktur & Sipil',
    location: 'Basement zona A',
    related_task_id: 102,
    due_date: daysFromNow(2),
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
  {
    id: 602,
    project_id: 1,
    created_by: 3,
    assigned_to: 2,
    communication_type: 'submittal',
    status: 'in_review',
    priority: 'critical',
    subject: 'SUB-002 Shop drawing MEP basement',
    description: 'Shop drawing rute ducting dan panel listrik menunggu review internal.',
    discipline: 'MEP',
    location: 'Basement B1-B2',
    due_date: daysFromNow(3),
    created_at: daysFromNow(-2),
    updated_at: daysFromNow(-1),
  },
  {
    id: 603,
    project_id: 1,
    created_by: 3,
    assigned_to: 5,
    communication_type: 'site_instruction',
    status: 'open',
    priority: 'medium',
    subject: 'SI-003 Perbaikan housekeeping akses tower crane',
    description: 'Rapikan material lepas dan pasang pembatas area sebelum shift malam.',
    discipline: 'K3 & Keselamatan',
    location: 'Akses tower crane sisi barat',
    due_date: daysFromNow(1),
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
  {
    id: 604,
    project_id: 1,
    created_by: 4,
    assigned_to: 2,
    communication_type: 'escalation',
    status: 'open',
    priority: 'critical',
    subject: 'ESC-004 Clash MEP dengan opening struktur',
    description: 'Pekerjaan struktur lantai basement berisiko tertahan bila keputusan belum keluar.',
    question: 'Perlu keputusan prioritas: revisi opening struktur atau realokasi jalur MEP?',
    discipline: 'MEP / Struktur',
    location: 'Basement B2',
    related_task_id: 102,
    due_date: daysFromNow(1),
    created_at: daysFromNow(-1),
    updated_at: daysFromNow(-1),
  },
]

export const demoStakeholders = [
  {
    name: 'PT Pembangunan Perumahan',
    type: 'Owner',
    project: 'Jakarta Central Tower',
    contact: 'project@pp.co.id',
    telegram: '@pp_project_team',
    health: 'Aktif',
    lastUpdate: 'Menerima risk alert dan weekly summary.',
  },
  {
    name: 'WIKA Foundation Team',
    type: 'Subkontraktor',
    project: 'Tol Serpong Paket 3',
    contact: 'foundation@wika.co.id',
    telegram: '@wika_foundation',
    health: 'Perlu follow-up',
    lastUpdate: 'Menunggu konfirmasi pompa tambahan.',
  },
  {
    name: 'AECOM Indonesia',
    type: 'Konsultan',
    project: 'RS Modular Bandung',
    contact: 'mep@aecom.com',
    telegram: '@aecom_mep',
    health: 'Aktif',
    lastUpdate: 'Review titik MEP modular ward.',
  },
]
